Import NumPy

In [ ]:
import numpy

NumPy as np

In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


Checking NumPy Version

In [3]:
print(np.__version__)

1.26.4


Create a NumPy ndarray Object 

In [5]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


Dimensions in Arrays

In [7]:
#0-D Arrays
arr = np.array(42)
print(arr)
print("\n")

#1-D Arrays
arr = np.array([[1,2,3], [4,5,6]])
print(arr)
print("\n")

#3-D arrays
arr = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])
print(arr)

42


[[1 2 3]
 [4 5 6]]


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


NumPy Array Indexing
Access Array Elements

In [ ]:
# Access 1-D Arrays
arr = np.array([1,2,3,4])
print(arr[0])

# Access 2-D Arrays
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0,1])

# Access 3-D Arrays
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(arr[0,1,2])

# Negative Indexing
print('Last element from 2nd dim: ', arr[1, -1])

Checking the Data Type of an Array

In [8]:
print(arr.dtype)

int64
